# Generated by Django 3.2.5 on 2021-08-16 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etitle', models.CharField(max_length=50)),
                ('edate', models.DateField()),
                ('edis', models.TextField()),
                ('epic', models.FileField(blank=True, null=True, upload_to='Event pic')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
