# Generated by Django 3.2.5 on 2021-08-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=100)),
                ('birth', models.DateField()),
                ('occupation', models.CharField(default='', max_length=100)),
                ('pic', models.FileField(blank=True, null=True, upload_to='holderpic/')),
                ('role', models.CharField(default='user', max_length=50)),
            ],
        ),
    ]
