# Generated by Django 3.2.5 on 2021-09-23 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatholder', '0002_complain'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentBuyHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rbaddress', models.CharField(max_length=100)),
                ('rbprice', models.CharField(max_length=50)),
                ('rbpic', models.FileField(blank=True, null=True, upload_to='Rent-Buy House')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flatholder.userf')),
            ],
        ),
    ]
