# Generated by Django 3.2.5 on 2021-09-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatholder', '0003_rentbuyhouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentbuyhouse',
            name='rbtype',
            field=models.CharField(default=10, max_length=50),
            preserve_default=False,
        ),
    ]
