# Generated by Django 3.2.5 on 2021-09-23 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatholder', '0004_rentbuyhouse_rbtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentbuyhouse',
            old_name='rbtype',
            new_name='type',
        ),
    ]
