# Generated by Django 3.2.5 on 2021-09-23 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatholder', '0005_rename_rbtype_rentbuyhouse_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentbuyhouse',
            old_name='type',
            new_name='type1',
        ),
    ]
