# Generated by Django 3.2.5 on 2021-09-28 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatholder', '0007_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
